const $ = (selector) => document.querySelector(selector);
const packages = [
  {name:'Umrah Economy',price:'349',days:7,description:'Affordable and organized spiritual package with standard hotel stay, guided group ziyarat, and seamless airport transport.',features:['3★ Hotel - Quad Sharing','Direct Airport Transfers','Umrah Visa Assistance','International Flight Support','Makkah & Madinah Ziyarat']},
  {name:'Umrah Premium',price:'499',days:10,description:'Our most beloved package featuring luxury 5-star hotels steps from the Holy Haram, full board buffet meals, and a dedicated scholar guide.',features:['5★ Hotel - Twin Sharing','Walking Distance To Haram','Full Board Buffet Meals','High-Speed Express Train','Dedicated Scholar Guide']},
  {name:'Hajj & Royal VIP',price:'1,199',days:14,description:'Ultra-luxury all-inclusive sacred experience with Haram-view suites, private chauffeured GMC transport, and personalized care.',features:['Haram View 5★ Suite','Private VIP GMC Chauffeur','Gourmet Dining Included','Fast-Track VIP Immigrations','Complimentary UAE Tour']}
];
$('#package-list').innerHTML = packages.map(p=>`<article class="package-card reveal"><div><p class="package-name">${p.name}</p><p class="price">$${p.price}<small> /${p.days} Days</small></p><p class="package-description">${p.description}</p><button class="split-button" data-book="${p.name}"><span>Get Started</span><i aria-hidden="true">➜</i></button></div><div class="package-included"><p>What's Included</p><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul></div></article>`).join('');
const scenes=['The Prophet’s Mosque in Madinah','Pilgrims around the Holy Kaaba','A pilgrim in prayer','The sacred courtyard in Makkah','Makkah Royal Clock Tower','The Holy Kaaba Kiswah'];
$('#photo-track').innerHTML = [...scenes,...scenes].map((alt,i)=>`<img src="assets/a${i%6+1}.png" alt="${i<6?alt:''}" ${i>=6?'aria-hidden="true"':''} loading="lazy">`).join('');
const services=[
  {name:'Visa Assistance',image:'1..png',alt:'Visa application passport and documents',description:'Complete Hajj And Umrah Visa Processing With Clear Guidance And Dedicated Support From Start To Finish.',features:['Visa Application Support','Application Processing','Document Checking','Travel Guidance']},
  {name:'Flight Booking',image:'2..png',alt:'Pilgrim at airport flight departure gate',description:'Direct And Connecting Flight Reservations With Top International Carriers, Optimized For Pilgrim Comfort And Baggage Allowance.',features:['Direct Flight Options','Group Seat Allocation','Extra Baggage Allowance','Airport Meet & Greet']},
  {name:'Hotel Accommodation',image:'3..png',alt:'Luxury hotel suite overlooking the Holy Kaaba',description:'Premium 3-Star, 4-Star, And Luxury 5-Star Properties Steps Away From The Holy Haram In Makkah And Madinah.',features:['Haram View Suites','Daily Buffet Breakfast','24/7 Concierge Service','Private Shuttle Transfers']}
];
$('#service-grid').innerHTML=services.map(s=>`<article class="service-column reveal"><img class="service-image" src="assets/${s.image}" alt="${s.alt}" loading="lazy"><div class="service-content"><h3>${s.name}</h3><p>${s.description}</p><strong>Included Services:</strong><ul>${s.features.map(f=>`<li>${f}</li>`).join('')}</ul><a class="split-button" href="#packages"><span>Explore Packages</span><i aria-hidden="true">↗</i></a></div></article>`).join('');
const steps=[['◇','Choose Your Package','Explore Our Hajj And Umrah Packages And Select The One That Matches Your Preferred Duration, Hotel, And Travel Needs.'],['▣','Book Your Journey','Contact Our Team, Confirm Your Package, And Complete The Booking With Clear Guidance At Every Step.'],['▤','Prepare Your Documents','We Help You Prepare And Verify The Required Documents And Provide Assistance Throughout The Visa Process.'],['✧','Begin Your Sacred Journey','Once Everything Is Ready, Travel With Confidence. Our Team Remains Available To Support You Throughout Your Entire Hajj Or Umrah Journey.']];
$('#timeline').innerHTML=steps.map(s=>`<article class="process-card reveal"><h3><span class="process-icon" aria-hidden="true">${s[0]}</span>${s[1]}</h3><p>${s[2]}</p></article>`).join('');
const destinations=[['Al-Masjid an-Nabawi','MADINAH',1],['Masjid al-Haram & Kaaba','MAKKAH',2],['Makkah Royal Sanctuary','MAKKAH',3],['Masjid al-Haram Courtyard','MAKKAH',4],['Makkah Royal Clock Tower','MAKKAH',5],['Holy Kaaba Kiswah Sanctuary','MAKKAH',6],['Medina Al-Munawwarah','MADINAH',1],['Sacred Tawaf Sanctuary','MAKKAH',2]];
$('#destination-grid').innerHTML=destinations.map(d=>`<figure class="destination-card reveal"><img src="assets/a${d[2]}.png" alt="${d[0]}" loading="lazy"><figcaption><h3>${d[0]}</h3><small>${d[1]}, SAUDI ARABIA</small></figcaption></figure>`).join('');
const quotes=[['Mohammad Rahman','From Visa Processing To Hotel Arrangements, Everything Was Clearly Explained And Exceptionally Well Organized.'],['Tariq Al-Mansoor','The 5-Star Hotel Steps From The Haram Made My Mother’s Umrah Effortless. The Scholar Guide Was Always By Our Side.'],['Dr. Fatima Zahra','Truly A VIP Experience. GMC Chauffeur Transfers And Seamless Fast-Track Airport Handling Exceeded All Our Family Expectations.'],['Zainab Begum','Heartwarming Hospitality And Smooth Wheelchair Support For My Elderly Parents. May Allah Reward The Entire Safar Team.'],['Farhan Choudhury','Every Single Promise Was Delivered Flawlessly. The Guided Ziyarat Tours Were Intellectually And Spiritually Enriching.']];
$('#testimonial-grid').innerHTML=quotes.map((q,i)=>`<article class="quote-card reveal"><div class="quote-top"><span>0${i+1} / PILGRIM STORIES</span><img src="assets/i${i+1}.png" alt="${q[0]}" loading="lazy"></div><blockquote>“${q[1]}”</blockquote><p class="quote-name">${q[0]}</p><div class="stars" aria-label="5 out of 5 stars">★★★★★</div></article>`).join('');
const faqs=[['Can I choose my hotel?','Yes, you have complete flexibility to choose your preferred hotel. We partner with leading 3-star, 4-star, and luxury 5-star properties steps away from the Holy Haram in both Makkah and Madinah.'],['Do you provide visa assistance?','Yes, comprehensive visa assistance is included in every package. We manage complete electronic visa processing, document verification, and submission with regular status updates from start to finish.'],['Do you arrange Ziyarat tours?','Yes, all our packages include guided Ziyarat tours to sacred historical sites in Makkah (Jabal al-Nour, Cave of Hira, Mina) and Madinah (Masjid Quba, Mount Uhud, Seven Mosques) led by knowledgeable scholars.'],['Can families or groups travel together?','Absolutely. We specialize in coordinated group and family bookings, providing interconnected rooms, private chauffeured transport, and customized itineraries tailored to elderly pilgrims and children.'],['Will I receive support during my journey?','Yes, our dedicated multilingual team is available 24/7 on the ground in both Makkah and Madinah, assisting you from airport arrival and check-in to spiritual guidance throughout your entire pilgrimage.']];
$('#faq-list').innerHTML=faqs.map((f,i)=>`<details name="faq" ${i===0?'open':''}><summary>${f[0]}</summary><p>${f[1]}</p></details>`).join('');
const menu=$('.menu-toggle');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');$('#nav-links').classList.toggle('open',open);menu.textContent=open?'×':'☰';});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');$('#nav-links').classList.remove('open');menu.textContent='☰';}));
const dialog=$('#booking');
document.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>{$('#booking-package').value=b.dataset.book;$('#booking-form').hidden=false;$('#enquiry-result').hidden=true;dialog.showModal();document.body.classList.add('modal-open');}));
$('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
const dateInput=$('input[type=date]');const today=new Date();dateInput.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
$('#booking-form').addEventListener('submit',event=>{event.preventDefault();const d=new FormData(event.target);const body=`Hello Safar team,\n\nI would like to enquire about ${d.get('package')}.\nName: ${d.get('name')}\nEmail: ${d.get('email')}\nTravellers: ${d.get('travellers')}\nPreferred travel date: ${d.get('date')}\n\nPlease share availability and details.\nThank you.`;$('#email-draft').href=`mailto:hello@safartravel.com?subject=${encodeURIComponent('Travel enquiry — '+d.get('package'))}&body=${encodeURIComponent(body)}`;event.target.hidden=true;$('#enquiry-result').hidden=false;$('#email-draft').focus();});
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
if(!reducedMotion.matches&&'IntersectionObserver' in window){document.body.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}else{$('.hero-video').pause();}
document.addEventListener('visibilitychange',()=>{const video=$('.hero-video');if(document.hidden||reducedMotion.matches)video.pause();else video.play().catch(()=>{});});
